# Generated by Django 3.0.3 on 2020-06-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Test description eath a hstha shta rsth sh sh rsj sr'),
            preserve_default=False,
        ),
    ]
