# Generated by Django 3.0.3 on 2020-06-02 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200602_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
