# Generated by Django 3.0.3 on 2020-06-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_last_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
