# Generated by Django 3.0.3 on 2020-06-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200602_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='last_updated_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(),
        ),
    ]
